from . import purchase_order
from . import purchase_order_line
from . import stock_move
from . import stock_picking
from . import sale_order
from . import sale_order_line
from . import res_partner
from . import maintenance
from . import model
from . import fuel
from . import invoice
